### PR TITLE
Add section about mix umbrella apps.

### PR DESCRIPTION
**Pull request by azizk**
Could've used this info today. Hope it helps others! Cheers! :)

### CODE REVIEW

**Comment by tsloughter** [comment]
I'm partly surprised to see that being how it has to be done, but not completely surprised because of how `mix`'s umbrella's are done (at least how I think they work).

Not that I don't believe you, but I'd like to get confirmation from someone who understands `mix` more than I do :).

In `rebar3` everything is based around it building 1 or more applications, so the plugin runs cover for all applications in the umbrella project. Maybe something similar could be done in the `mix` task instead of requiring the user to do this work each time?

**Comment by azizk** [comment]
Hey, no problem. I also found it difficult to believe. I investigated a little but I couldn't find a clue regarding this case. Afaics umbrella projects are basically containers with convenience functions. When `mix test` is entered at the root dir, mix runs the test-suite within each app one after the other. So there's probably no chance for rebar to get all the apps across all test-suites in order to generate a single coverage file. Maybe I'm missing something but that's what I know so far. :)

**Comment by azizk** [comment]
So I incidentally checked out excoveralls while looking at a commit of another Elixir project. Looks like it provides an `--umbrella` option for combining all the sub-app statistics into one report file.

Would be cool to have the same option in your project. Even better make it the default (detect if it's an umbrella) and have an option for separate reports if that's preferred.

**Comment by tsloughter** [comment]
+1 to making it the default.

If you are running cover at the top level of a project I think it can be assumed the user wants to run cover on the apps in the project.

**Comment by azizk** [comment]
Closing this due to inactivity, but feel free to integrate the changes if needed.

**Pull request closed without merging**
